### ISSUE TITLE
Kicked Off Event Page When Removing Horses From Second Race

### ISSUE THREAD

**Issue by nicholasklaene** [brewerc1/family-races#223]
You are kicked off of the event page when creating a second race and removing horses from it. Video of the bug: https://www.awesomescreenshot.com/video/3315461?key=3cd6f092268e43380ecd69b00ad86d94

**Comment by makungaj1** [comment]
We need to discuss about the potential fix for this issue.

**Comment by nicholasklaene** [comment]
Looking into this now.

**Comment by makungaj1** [comment]
This is a easy fix UI fix. I'd like to discuss it before we implement the fix.
