### ISSUE TITLE
Horse name field - WTF

### ISSUE THREAD

**Issue by brewerc1** [brewerc1/family-races#231]
The DB supports 64 chars for horse name. The backend apparently doesn't like more than 48. The frontend is completely oblivious and lets the user enter any number of characters. On top of it all, the backend throws a generic "SERVER ERROR" message if the enduser doesn't know all these mis-matched secrets.

**Comment by nicholasklaene** [comment]
Will fix this tommorow.

Going to add a guard for the POST endpoint & truncate all strings to max 48 chars.
